spring:
  datasource-onec-database:
    jdbcUrl: jdbc:sqlserver://${hostname}:1433;databaseName=ARM;encrypt=false
    username: ----
    password: ----
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  datasource-internal-database:
    jdbcUrl: jdbc:sqlserver://${hostname}:1433;databaseName=gj_receiving;encrypt=false
    username: ----
    password: ----
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: 8082
  address: 0.0.0.0
  jetty:
    threads:
      max: 4
      min: 2
onec:
  md:
    path: "D:/ARM/****"

idd-generator:
  url: "http://${hostname}:8081/idd/generator"

marks:
  server:
    url: "http://azr-package-db.gloria.aaanet.ru:9010"
    authorization:
      url: "https://rnd-netsso.gloria.aaanet.ru/auth"
      username: "*****"
      password: "*****"


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, info